### ISSUE TITLE
关于video_loader.py第99行的问题

### ISSUE THREAD

**Issue by 1691077362** [guxinqian/TKP#7]
我运行你的代码出现了如下的问题，请问是怎么回事。
Traceback (most recent call last):
  File "train.py", line 463, in <module>
    main()
  File "train.py", line 200, in main
    train(epoch, vid_model, img_model, classifier, criterion, criterion_tkp_f, criterion_tkp_d, criterion_i2v, optimizer, trainloader, use_gpu)
  File "train.py", line 253, in train
    for batch_idx, (vids, pids, _) in enumerate(trainloader):
  File "C:\Users\administer\.conda\envs\p\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\administer\.conda\envs\p\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "C:\Users\administer\.conda\envs\p\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "C:\Users\administer\.conda\envs\p\lib\site-packages\torch\_utils.py", line 434, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\administer\.conda\envs\p\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\administer\.conda\envs\p\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\administer\.conda\envs\p\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\YDH\spxrcsb\TKP-master\utils\video_loader.py", line 99, in __getitem__
    clip = torch.stack(clip, 0).permute(1, 0, 2, 3)
RuntimeError: stack expects a non-empty TensorList

**Comment by guxinqian** [comment]
字面意思是你的clip是空的，你可以检查下你的数据或者clip前的代码有没有问题

**Comment by 1691077362** [comment]
好的

**Comment by 1691077362** [comment]
你能分享一下你所使用的数据集吗，我怀疑是我下载的数据集和你所使用的不太一样。我怀疑应该是目录有问题。
![Uploading 捕获.PNG…]()

**Comment by 1691077362** [comment]
你能分享一下你所使用的数据集吗，我怀疑是我下载的数据聚集在目录上和你的有所差别。就像这样：
![捕获](https://user-images.githubusercontent.com/91247734/181445944-fc5dde0a-8702-43a2-9969-06dc581c7d83.PNG)

**Comment by 1691077362** [comment]
你能详细分享一下你数据集的存放目录吗？谢谢

**Comment by guxinqian** [comment]
data/
----DukeMTMC-VideoReID
----MARS
----iLIDS-VID

**Comment by 1691077362** [comment]
/data/datasets/MARS/bbox_train
/data/datasets/MARS/bbox_test
这么放对吧

**Comment by guxinqian** [comment]
对的，路径没问题，你可以检查下是不是有些样本丢了

**Comment by guxinqian** [comment]
或者Windows下的路径是不是改改成双斜杠

**Comment by 1691077362** [comment]
好的，谢谢。麻烦你了。

**Comment by 1691077362** [comment]
python train.py --root /data/datasets/ -d mars --save_dir log-mars
这个mars文件夹中存放的是什么数据啊，放的也是数据集吗
mars/bbox_train
mars/bbox_test

和MARS文件夹存放的数据集是一样吗
/data/datasets/MARS/bbox_train
/data/datasets/MARS/bbox_test

**Comment by 1691077362** [comment]
python train.py --root /data/datasets/ -d mars --save_dir log-mars
这个mars文件夹中存放的是什么啊，放的也是数据集吗
mars/bbox_train
mars/bbox_test

和MARS文件夹存放的数据集是一样吗
/data/datasets/MARS/bbox_train
/data/datasets/MARS/bbox_test
/data/datasets/MARS/info

**Comment by 1691077362** [comment]
mars这个文件夹放在哪里啊
是这么放的吗/data/datasets/mars

**Comment by 1691077362** [comment]
![捕获](https://user-images.githubusercontent.com/91247734/181696881-d438a02a-7f65-4173-aabd-fa53e0cf61af.PNG)
![捕获1](https://user-images.githubusercontent.com/91247734/181696882-9a80e03d-0012-43fc-970d-76e1af8da0ff.PNG)
![捕获2](https://user-images.githubusercontent.com/91247734/181696883-bfa0714f-3a50-4aa6-9d95-6e7e47039d80.PNG)
![捕获3](https://user-images.githubusercontent.com/91247734/181696887-60cac7b4-35b1-4d51-82bc-0e19d9236888.PNG)
![捕获4](https://user-images.githubusercontent.com/91247734/181696890-8daf8475-9243-4b3e-b89e-f2f33cfaa8ae.PNG)
![捕获5](https://user-images.githubusercontent.com/91247734/181696892-39b82355-709b-4093-99e3-158b80163b35.PNG)
![捕获6](https://user-images.githubusercontent.com/91247734/181696895-acecf6d2-4c93-4382-b63e-6d2232ffb542.PNG)
我在 start train出现这个错误，我改完路径后start train不出现这个错误了。但是在test部分出现这个错误了，所以我想知道我的路径是否还有问题。
==> Start training
C:\Users\administer\.conda\envs\p\lib\site-packages\torch\optim\lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
F:\YDH\spxrcsb\TKP-master\utils\losses.py:108: UserWarning: This overload of addmm_ is deprecated:
        addmm_(Number beta, Number alpha, Tensor mat1, Tensor mat2)
Consider using one of the following signatures instead:
        addmm_(Tensor mat1, Tensor mat2, *, Number beta, Number alpha) (Triggered internally at  ..\torch\csrc\utils\python_arg_parser.cpp:1050.)
  img_distmat.addmm_(1, -2, images, images.t())
Epoch1 Time:593.4s Data:17.5s vXent:6.6427 iXent:6.6635 TKP_F:4.4849 TKP_D:0.4471 i2v:0.2863 v2i:0.4856 i2i:0.5366 v2v:0.2403 vAcc:3.37% iAcc:3.37%
==> Test
Extract video features
Traceback (most recent call last):
  File "train.py", line 471, in <module>
    main()
  File "train.py", line 208, in main
    rank1 = test(vid_model, img_model, queryloader, galleryloader, queryimgloader, galleryimgloader, use_gpu)
  File "train.py", line 341, in test
    for batch_idx, (vids, pids, camids) in enumerate(queryloader):
  File "C:\Users\administer\.conda\envs\p\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\Users\administer\.conda\envs\p\lib\site-packages\torch\utils\data\dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\administer\.conda\envs\p\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\administer\.conda\envs\p\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "F:\YDH\spxrcsb\TKP-master\utils\video_loader.py", line 116, in __getitem__
    clip = torch.stack(clip, 0).permute(1, 0, 2, 3)
RuntimeError: stack expects a non-empty TensorList

**Comment by guxinqian** [comment]
我也不知道，没在windows下跑过，不行你改Linux试试
